export const FETCHING_BITTREX_DATA = "FETCHING_BITTREX_DATA";
export const FETCHING_BITTREX_DATA_SUCCESS = "FETCHING_BITTREX_DATA_SUCCESS";
export const FETCHING_BITTREX_DATA_FAIL = "FETCHING_BITTREX_DATA_FAIL";
export const FETCHING_POLONIEX_DATA = "FETCHING_POLONIEX_DATA";
export const FETCHING_POLONIEX_DATA_SUCCESS = "FETCHING_POLONIEX_DATA_SUCCESS";
export const FETCHING_POLONIEX_DATA_FAIL = "FETCHING_POLONIEX_DATA_FAIL";
export const MAIN_COIN_CHANGE = "MAIN_COIN_CHANGE";
export const SECOND_COIN_CHANGE = "SECOND_COIN_CHANGE";
