export const FETCHING_BITTREX_DATA = "FETCHING_BITTREX_DATA";
export const FETCHING_BITTREX_DATA_SUCCESS = "FETCHING_BITTREX_DATA_SUCCESS";
export const FETCHING_BITTREX_DATA_FAIL = "FETCHING_BITTREX_DATA_FAIL";
